# Spring properties
spring:
  application:
    name: email-service
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: email-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.johara.email
        value.default.type: com.johara.email.model.OrderMessage

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 2224   # HTTP (Tomcat) port